### ISSUE TITLE
Notebooks are not working or running using a MyBinder session

### ISSUE THREAD

**Issue by GuillaumeVandekerckhove** [highcharts-for-python/highcharts-for-python-demos#4] opened 2023-04-28 13:06 UTC
Dear,

The notebooks don't give any results using a MyBinder session. 

I get two types of errors:
1. _500: Internal Server Error_ and jupyter lab doesn't open
2. Jupyter lab opens, I can run the notebooks but I get the respons: 
_Something went wrong with the Highcharts.js script. It should have been automatically loaded, but it did not load for over 3 seconds. Check your internet connection, and then if the problem persists please reach out for support._

Greetings,
Guillaume

**Comment by hcpchris** [comment] 2023-04-28 13:50
Thanks, @GuillaumeVandekerckhove : It seems that MyBinder is having some issues with its container image (for example, I can't even spin up a MyBinder session right now because the container image pull is failing on the MyBinder side). I'll push a commit to this repo to make MyBinder rebuild its container image, and hopefully that will address the underlying issue.

**Comment by hcpchris** [comment] 2023-04-28 14:00
@GuillaumeVandekerckhove : I've pushed an updated set of requirements (and added another demo in the meantime) to the repo, and merged that commit into the main branch. MyBinder is currently rebuilding the image, however it seems to be having various issues/problems on their side as it does this. 

It seems seems like this may be tied to some fairly substantial infrastructure issues happening on the MyBinder side. You can find a post from the MyBinder team about this [here](https://discourse.jupyter.org/t/mybinder-org-reducing-capacity-unstable/19163). It seems that MyBinder is currently (at least as of 18h ago) unstable, which is causing various issues, and which I suspect may be causing various issues with the MyBinder service. 

I'll keep an eye on this, and see if I can reproduce the issues you are running into once MyBinder gets more stable (hopefully soon).

**Comment by hcpchris** [comment] 2023-04-28 14:17
@GuillaumeVandekerckhove : So after some time, MyBinder was able to spin up the Jupyter Lab environment successfully, and I was able to get the demos to render the charts. I strongly suspect that the issues you are seeing are a consequence of the infrastructure problems that MyBinder is having. 

As a workaround while they try to find a solution for their infrastructure issues, you can:
1. Checkout the repo locally,
2. Create (and activate!) a virtual environment
3. `pip install -r requirements.txt`
4. Spin up Jupyter Lab in that repo,
5. and try the demo's locally.

For the time being, I'll close this issue and update the README to mention the MyBinder infrastructure problems. However, if you run into issues running the demos in a local environment, please feel free to either log a new issue or re-open this one. Thanks for bringing this to my attention! I didn't realize that MyBinder started having these infrastructure challenges yesterday.

**Closed as completed** 2023-04-28 14:18 UTC
Labels: wontfix

**Comment by GuillaumeVandekerckhove** [comment] 2023-04-28 14:26
Thanks for checking this and defining the problem!
